global:
  scrape_timeout_offset: 500ms
  min_interval: 0s
  max_connections: 3
  max_idle_connections: 3
target:
  data_source_name: 'mysql://${exporter_username}:${exporter_password}@tcp(${exporter_hostname})/information_schema?tls=skip-verify'
  collectors:
  - mysql
collector_files:
- "/etc/sql-exporter-querries/mysql.yml"
