apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ${cluster_issuer_name}
spec:
  acme:
    server: ${server}
    email: '${email}'
    privateKeySecretRef:
      name: ${cluster_issuer_name}
    http01: {}
