apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ${cluster_issuer_staging}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: '${email}'
    privateKeySecretRef:
      name: ${cluster_issuer_staging}
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: ${cluster_issuer_prod}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: '${email}'
    privateKeySecretRef:
      name: ${cluster_issuer_prod}
    http01: {}
