# See the official documentation here: https://kubernetes.github.io/ingress-nginx/deploy/#mandatory-command
# This templates come from https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: ingress-nginx
