# See the official documentation here: https://kubernetes.github.io/ingress-nginx/deploy/#mandatory-command
# This templates come from https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
  namespace: ingress-nginx
