apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${namespace}
subjects:
- kind: ServiceAccount
  name: ${namespace}
  namespace: ${namespace}

